import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View, FlatList, ActivityIndicator, RefreshControl, TouchableOpacity, Alert, TextInput } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

// Type definitions
interface ScanItem {
  _id: string;
  diagnosis: string;
  timestamp: string;
  confidence_score: number;
  [key: string]: any;
}

export default function HistoryScreen() {
  const [scans, setScans] = useState<ScanItem[]>([]);
  const [filteredScans, setFilteredScans] = useState<ScanItem[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const API_URL = "http://192.168.1.2:8000";

  const fetchHistory = async () => {
    try {
      const response = await fetch(`${API_URL}/api/history`);
      const data: ScanItem[] = await response.json();
      setScans(data);
      setFilteredScans(data); // Initialize filtered list
    } catch (error) {
      console.error("Fetch failed:", error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  // Real-time Search Logic
  const handleSearch = (text: string) => {
    setSearchQuery(text);
    if (text === '') {
      setFilteredScans(scans);
    } else {
      const filtered = scans.filter((item: ScanItem) => 
        item.diagnosis.toLowerCase().includes(text.toLowerCase())
      );
      setFilteredScans(filtered);
    }
  };

  const deleteScan = (id: string) => {
    Alert.alert("Delete Record", "Remove this scan from the app database?", [
      { text: "Cancel", style: "cancel" },
      { 
        text: "Delete", 
        style: "destructive", 
        onPress: async () => {
          try {
            const response = await fetch(`${API_URL}/api/history/${id}`, { method: 'DELETE' });
            if (response.ok) {
              const updated = scans.filter((item: ScanItem) => item._id !== id);
              setScans(updated);
              setFilteredScans(updated);
            }
          } catch (error) {
            console.error('Delete error:', error);
            Alert.alert("Error", "Could not connect to backend.");
          }
        } 
      }
    ]);
  };

  const downloadPDF = async (item: ScanItem) => {
  const htmlContent = `
    <html>
      <body style="font-family: 'Helvetica'; padding: 40px; color: #333;">
        <h1 style="color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px;">
          arogya_app Diagnostic Report
        </h1>
        <div style="margin-top: 20px; font-size: 16px;">
          <p><strong>Record ID:</strong> ${item._id}</p>
          <p><strong>Date:</strong> ${new Date(item.timestamp).toLocaleString()}</p>
          <hr />
          <h2 style="color: #d93025;">Analysis Result: ${item.diagnosis}</h2>
          <p><strong>AI Confidence Score:</strong> ${item.confidence_score}%</p>
        </div>
        <footer style="margin-top: 50px; font-size: 12px; color: #777; text-align: center;">
          Generated by Vaidya Voice Mobile System • arogya_app
        </footer>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('PDF generation error:', error);
    Alert.alert("Error", "Could not generate PDF report.");
  }
};

  useEffect(() => {
    fetchHistory();
  }, []);

  if (loading) return <ActivityIndicator size="large" style={{ flex: 1 }} />;

  return (
  <View style={styles.container}>
    {/* Clean, Branded Header */}
    <View style={styles.headerCard}>
      <Text style={styles.title}>arogya_app Records</Text>
      <Text style={styles.subHeader}>Field Diagnostic History</Text>
    </View>
    
    <TextInput
      style={styles.searchBar}
      placeholder="Search diagnosis..."
      value={searchQuery}
      onChangeText={handleSearch}
      clearButtonMode="while-editing"
    />

    <FlatList
      data={filteredScans}
      keyExtractor={(item) => item._id}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={fetchHistory} />}
      renderItem={({ item }) => (
        <View style={styles.card}>
          <View style={{ flex: 1 }}>
            <Text style={styles.diagnosis}>{item.diagnosis}</Text>
            <Text style={styles.date}>{new Date(item.timestamp).toLocaleDateString()}</Text>
          </View>
          <View style={styles.rightSection}>
            <Text style={styles.confidence}>{item.confidence_score}%</Text>
            <View style={{ flexDirection: 'row', gap: 12 }}>
              <TouchableOpacity onPress={() => downloadPDF(item)} style={styles.pdfBtn}>
                <Text style={{ fontSize: 18 }}>📄</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => deleteScan(item._id)} style={styles.deleteBtn}>
                <Text style={{ fontSize: 18 }}>🗑️</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      )}
    />
  </View>
);
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa', padding: 20 },
  headerCard: {
    marginTop: 40,
    marginBottom: 20,
  },
  title: { fontSize: 28, fontWeight: '800', color: '#1a73e8' },
  subHeader: { fontSize: 14, color: '#5f6368', fontWeight: '500' },
  searchBar: {
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    fontSize: 16,
  },
  card: { backgroundColor: '#fff', padding: 15, borderRadius: 12, marginBottom: 12, flexDirection: 'row', alignItems: 'center', elevation: 2 },
  diagnosis: { fontSize: 18, fontWeight: '600', color: '#333' },
  date: { fontSize: 13, color: '#666', marginTop: 4 },
  rightSection: { alignItems: 'flex-end', justifyContent: 'center' },
  confidence: { color: '#1a73e8', fontWeight: 'bold', marginBottom: 8 },
  pdfBtn: { backgroundColor: '#e8f0fe', padding: 8, borderRadius: 10 },
  deleteBtn: { backgroundColor: '#feeef3', padding: 8, borderRadius: 10 },
  actionBtn: { padding: 5 },
  emptyText: { textAlign: 'center', color: '#999', marginTop: 20 }
});